[ids]

*
[main]
# overload(hold,tick)
a = lettermod(control, a, 200, 100)
s = lettermod(shift, s, 200, 100)
d = lettermod(alt, d, 200, 100)
f = lettermod(meta, f, 200, 100)

semicolon = lettermod(control, semicolon, 200, 100)
l = lettermod(shift, l, 200, 100)
k = lettermod(alt, k, 200, 100)
j = lettermod(meta, j, 200, 100)
# apostrophe = overload(shift,apostrophe)

space = overload(spacelay,space)

[spacelay]
m = layer(shift)
n = layer(control)
e = up
d = down
s = left
f = right
q = home
t = end
w = C-left
r = C-right
a = enter
g = backspace
h = delete

k = pagedown
i = pageup

z = C-z
x = C-x
c = C-c
v = C-v

1 = S-1
2 = S-2
3 = S-3
4 = S-4
5 = S-5
6 = S-6
7 = S-7
8 = S-8
9 = S-9
0 = S-0
- = S--
= = S-=
[ = S-[
] = S-]
; = S-;
' = S-'
, = S-,
. = S-.
\ = S-\
` = S-`
/ = S-/
