[ids]

*
m:046d:c548
[main]
# overload(hold,tick)
a = lettermod(control, a, 350, 180)
s = lettermod(shift, s, 350,  180)
d = lettermod(alt, d, 350, 180)
f = lettermod(meta, f, 350, 180)

semicolon = lettermod(control, semicolon, 350, 180)
l = lettermod(shift, l, 350, 180)
k = lettermod(alt, k, 350, 180)
j = lettermod(meta, j, 350, 180)
# apostrophe = overload(shift,apostrophe)

space = overload(spacelay,space)

rightmouse = overload(rm,rightmouse)

[rm]
rightmouse = rightmouse
leftmouse = leftmeta
middlemouse = A-f4
mouse2 = volumeup
mouse1 = volumedown

[spacelay]
m = layer(shift)
n = layer(control)
e = up
d = down
s = left
f = right
q = home
t = end
w = C-left
r = C-right
a = enter
g = backspace
h = delete

k = pagedown
i = pageup

z = C-z
x = C-x
c = C-c
v = C-v

1 = S-1
2 = S-2
3 = S-3
4 = S-4
5 = S-5
6 = S-6
7 = S-7
8 = S-8
9 = S-9
0 = S-0
- = S--
= = S-=
[ = S-[
] = S-]
; = S-;
' = S-'
, = S-,
. = S-.
\ = S-\
` = S-`
/ = S-/
